### ISSUE TITLE
[BUG] Direct Messages do not work; the app crashes instead of displaying DMs

### ISSUE THREAD

**Issue by GoDzM4TT3O** [austinhuang0131/instagrabber#25]
Direct Messages (DMs) do not work, the app crashes.

## Steps

1. Open the app
2. Press the "Direct Messages" button
3. The app crashes

### Expected Behaviour

I should see my DMs; instead, the app crashes.

## Screenshots

![20200804_131504.png](https://user-images.githubusercontent.com/28765699/89287667-add16680-d654-11ea-97eb-5ec325cdaf07.png)

![20200804_131550.png](https://user-images.githubusercontent.com/28765699/89287769-d35e7000-d654-11ea-8285-e9970f8afb69.png)

## Environment

 - Device: Samsung Galaxy A50
 - Android version: 10
 - App version: 17.1

## Additional info

My phone is not rooted.

Here are the logs:

```


New Trace collected:
=====================
Error report collected on: Tue Aug 04 13:15:10 GMT+02:00 2020

Information:
==============
VERSION		: 17.1
VERSION_CODE	: 37
PHONE-MODEL	: SM-A505FN
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: samsung
MANUFACTURER	: samsung
BOARD			: exynos9610
DEVICE			: a50
PRODUCT		: a50eea
HOST			: [hidden]
TAGS			: release-keys

Stack:
==============
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at awais.instagrabber.adapters.DirectMessagesAdapter.onBindViewHolder(DirectMessagesAdapter.java:67)
	at awais.instagrabber.adapters.DirectMessagesAdapter.onBindViewHolder(DirectMessagesAdapter.java:26)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7163)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7243)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6110)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6376)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6216)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6212)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4215)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3926)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4484)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1058)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3679)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3139)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:729)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Cause:
==============

**** End of current Report ***
New Trace collected:
=====================
Error report collected on: Tue Aug 04 13:19:26 GMT+02:00 2020

Information:
==============
VERSION		: 17.1
VERSION_CODE	: 37
PHONE-MODEL	: SM-A505FN
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: samsung
MANUFACTURER	: samsung
BOARD			: exynos9610
DEVICE			: a50
PRODUCT		: a50eea
HOST			: [hidden]
TAGS			: release-keys

Stack:
==============
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at awais.instagrabber.adapters.DirectMessagesAdapter.onBindViewHolder(DirectMessagesAdapter.java:67)
	at awais.instagrabber.adapters.DirectMessagesAdapter.onBindViewHolder(DirectMessagesAdapter.java:26)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7163)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7243)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6110)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6376)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6216)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6212)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4215)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3926)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4484)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1058)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3679)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3139)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:729)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Cause:
==============

**** End of current Report ***
New Trace collected:
=====================
Error report collected on: Tue Aug 04 13:17:53 GMT+02:00 2020

Information:
==============
VERSION		: 17.1
VERSION_CODE	: 37
PHONE-MODEL	: SM-A505FN
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: samsung
MANUFACTURER	: samsung
BOARD			: exynos9610
DEVICE			: a50
PRODUCT		: a50eea
HOST			: [hidden]
TAGS			: release-keys

Stack:
==============
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at awais.instagrabber.adapters.DirectMessagesAdapter.onBindViewHolder(DirectMessagesAdapter.java:67)
	at awais.instagrabber.adapters.DirectMessagesAdapter.onBindViewHolder(DirectMessagesAdapter.java:26)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7163)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7243)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6110)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6376)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6216)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6212)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4215)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3926)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4484)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1058)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3679)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3139)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:729)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Cause:
==============

**** End of current Report ***

```

Note: I manually hid "HOST" with "[hidden]".

**Comment by austinhuang0131** [comment]
See if new version works; if not (or if DM shows blank screen but you do have convos) I need:

* An approximate count
* Message type of the last message of each convo, including actions (leave, kick...), IF it is not one of:
  * Text/Media
  * Post/Story share (public)

**Comment by GoDzM4TT3O** [comment]
Sadly they still do not work. Just like before, they crash.

**Comment by austinhuang0131** [comment]
clearing cache is not going to help, the app only caches images through Glide

my theory is that the last message of your first convo contains something that's not a "normal" type of message

**Comment by GoDzM4TT3O** [comment]
You're right, my friend sent me a post.
Maybe I should ask him to send me a normal text message to see if they work. I'll let you know in a minute.
-------- Original Message --------

**Comment by austinhuang0131** [comment]
Private post (ie. you can't see it)?

Also you can just send a normal text message yourself, your own messages also count

**Comment by GoDzM4TT3O** [comment]
Nope, it was a public page.

Also still doesn't work with text only.

**Comment by austinhuang0131** [comment]
At this point I don't think I can easily fix this without asking for a bunch of account info (which obviously is against privacy) but I'll keep an eye on that

**Comment by austinhuang0131** [comment]
Check debug logs (in settings). I think DM inbox has an extremely low ratelimit.

```
2020-08-05 12:07:39.464 5791-5832/me.austinhuang.instagrabber E/AWAISKING_APP: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:112)
        at org.json.JSONObject.<init>(JSONObject.java:168)
        at org.json.JSONObject.<init>(JSONObject.java:181)
        at awais.instagrabber.asyncs.direct_messages.InboxFetcher.doInBackground(InboxFetcher.java:47)
        at awais.instagrabber.asyncs.direct_messages.InboxFetcher.doInBackground(InboxFetcher.java:25)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by austinhuang0131** [comment]
patched (not fully fixed) [v17.4](https://github.com/austinhuang0131/instagrabber/releases/tag/v17.4)

this happens when a dm thread of yours does not have an avatar

**Comment by GoDzM4TT3O** [comment]
Fixed! It works now!

**Comment by austinhuang0131** [comment]
oh ok now i realized why

if someone left a one-on-one dm then the dm would have no members
