### ISSUE TITLE
No feed loading [BUG]

### ISSUE THREAD

**Issue by Matt-Mf** [austinhuang0131/instagrabber#76]
Impressive work, good project.

## Bug

Feed doesn't load.

## Environment

 - Device: Fire HD 8 - 2017
 - Android version: LineageOS 12.1 - Android 5.1.1

## Additional info

----------------- doInBackground ------------------
org.json.JSONException: Value null at user of type org.json.JSONObject$1 cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:100)
	at org.json.JSONObject.getJSONObject(JSONObject.java:613)
	at awais.instagrabber.asyncs.FeedFetcher.doInBackground(FeedFetcher.java:65)
	at awais.instagrabber.asyncs.FeedFetcher.doInBackground(FeedFetcher.java:27)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

----------------- doInBackground ------------------
org.json.JSONException: Value null at user of type org.json.JSONObject$1 cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:100)
	at org.json.JSONObject.getJSONObject(JSONObject.java:613)
	at awais.instagrabber.asyncs.FeedStoriesFetcher.doInBackground(FeedStoriesFetcher.java:44)
	at awais.instagrabber.asyncs.FeedStoriesFetcher.doInBackground(FeedStoriesFetcher.java:22)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by austinhuang0131** [comment]
Can you load private profiles?

If not, can you load public profiles?

If not, is your login being considered suspicious by Instagram (check browser), or if you're using a VPN/Proxy?

**Comment by Matt-Mf** [comment]
Thanks.

Can you load followed private profiles and Discover? **NO**

If not, can you load public profiles? **YES**

If not, are you logging in from Quick Access? **YES**

If not, is your login being considered suspicious by Instagram? **NO**

If not, are you using a VPN/Proxy? **NO**

I'm using Netguard but the issue persists even when i disable it.

**Comment by austinhuang0131** [comment]
Log in again.

Quick Access doesn't check cookie validity, and we can't store passwords.

**Comment by Matt-Mf** [comment]
Already done. Same results.

**Comment by austinhuang0131** [comment]
Well... It's definitely not a coding error, because it's basically "can't parse json"

This leaves 2 options:

* The app somehow erased the cookie: If you know how to do mitmproxy and stuff then you can try to test it for me, but I certainly don't expect you do, so I'll try to go through all the hoops
* The cookie still exists, but Instagram blocked the cookie: No can do

**Comment by Matt-Mf** [comment]
Thanks for your patience.
I've digged into instagram settings and found that it labels the access as suspicious every time. (this was you?...)

Any other advice?

**Comment by austinhuang0131** [comment]
of course it's suspicious every time, do they like me not feeding tracking data to them?

**Comment by Matt-Mf** [comment]
I'll research this and I'll report it if find something interesting regarding this issue.

**Comment by Matt-Mf** [comment]
Very similar error: [https://stackoverflow.com/questions/50596457/value-null-at-json-key-object-of-type-org-json-jsonobject1-cannot-be-converte/50598341#](url)

**Comment by austinhuang0131** [comment]
Again, JSON parse error doesn't mean it's a code issue, it means Instagram is returning bad data that the app cannot parse, which usually caused by login issues

**Comment by austinhuang0131** [comment]
[Might have been fixed.](https://github.com/austinhuang0131/instagrabber/commit/86a90aff5c52f3b84396c37e506e56eeebc4189c)

Will push on next release (ETA unknown).

**Comment by legkamran** [comment]
I am using the same version and everything is allright... maybe log out and log in will solve problem becouse I done it before

**Comment by austinhuang0131** [comment]
@legkamran depends on android version, users below android 8-ish have this problem

**Comment by austinhuang0131** [comment]
Added in v18.2
